### ISSUE TITLE
Ubuntu 12.04 build fails

### ISSUE THREAD

**Issue by paskal** [paskal/SoftEtherVPN-debianisation#4]
[Example](https://launchpadlibrarian.net/392488033/buildlog_ubuntu-precise-amd64.softether-vpn_5.01.9662~201810081900~ubuntu12.04.1_BUILDING.txt.gz), error is:

    /<<PKGBUILDDIR>>/src/Mayaqua/cpu_features/src/hwcaps.c:54:22: fatal error: sys/auxv.h: No such file or directory

**Comment by paskal** [comment]
@davidebeatrici @chipitsine maybe you could advise what could be done here? It seems to be related with old libraries (libc?) version, from obvious things I could try embedding this file as pre-build step (with which content?) manually, but I'm not sure just one will be enough.

**Comment by chipitsine** [comment]
I wished to enable 12.04 builds on gitlab-ci

https://github.com/SoftEtherVPN/SoftEtherVPN/blob/master/.gitlab-ci.yml#L26-L32

feel free to make pull request if you will figure out how to build on 12.04 (I stuck on too old gcc compiler)

**Comment by paskal** [comment]
@chipitsine, that's the easy part: just enable cmake v3.9.6 instead of v3.12.1, because it's the last version which builds with GCC without g++11 support - let's see what it says then.

**Comment by davidebeatrici** [comment]
Ubuntu 12.04 has glibc 2.15, `getauxval()` was added in 2.16.

As a workaround we can use something like:
```c
--- /src/Mayaqua/cpu_features/src/hwcaps.c
+++ /src/Mayaqua/cpu_features/src/hwcaps.c
@@ -48,15 +48,6 @@
 // Implementation of GetElfHwcapFromGetauxval
 ////////////////////////////////////////////////////////////////////////////////
 
-// On Linux we simply use getauxval.
-#if defined(HWCAPS_REGULAR_LINUX)
-#include <dlfcn.h>
-#include <sys/auxv.h>
-static unsigned long GetElfHwcapFromGetauxval(uint32_t hwcap_type) {
-  return getauxval(hwcap_type);
-}
-#endif  // defined(HWCAPS_REGULAR_LINUX)
-
 // On Android we probe the system's C library for a 'getauxval' function and
 // call it if it exits, or return 0 for failure. This function is available
 // since API level 20.
@@ -71,7 +62,7 @@
 // implementation does not parse /proc/self/auxv. Instead it depends on values
 // that are passed by the kernel at process-init time to the C runtime
 // initialization layer.
-#if defined(HWCAPS_ANDROID_MIPS_OR_ARM)
+#if defined(HWCAPS_REGULAR_LINUX) || defined(HWCAPS_ANDROID_MIPS_OR_ARM)
 #include <dlfcn.h>
 #define AT_HWCAP 16
 #define AT_HWCAP2 26
@@ -101,7 +92,7 @@
   dlclose(libc_handle);
   return ret;
 }
-#endif  // defined(HWCAPS_ANDROID_MIPS_OR_ARM)
+#endif  // defined(HWCAPS_REGULAR_LINUX) || defined(HWCAPS_ANDROID_MIPS_OR_ARM)
 
 #if defined(HWCAPS_SUPPORTED)
 ////////////////////////////////////////////////////////////////////////////////
```

**Comment by paskal** [comment]
Thanks! I think this patch could be improved in some way it would not affect new glibc but detect old one. I'll test Ilya's repo version to see if it will help.

**Comment by davidebeatrici** [comment]
You're welcome!

@chipitsine's commit is not going to build because the `cpu_features` headers are still included in `Mayaqua/Encrypt.c`, resulting in a linker error.

Also, I think that it's better if we are able to use `cpu_features` for Ubuntu 12.04 too.

**Comment by paskal** [comment]
@chipitsine, [here](https://launchpadlibrarian.net/392496789/buildlog_ubuntu-precise-amd64.softether-vpn_5.01.9662~201810092022~ubuntu12.04.1_BUILDING.txt.gz) is the log, current error is:
```Unknown CMake command "check_include_file".```

**Comment by chipitsine** [comment]
hi, can you have a look https://github.com/chipitsine/SoftEtherVPN/commit/de56224cdbb0a0b63a8cdb632f239531d79e0685 ?

I would like to estimate how long we wish to support ubuntu 12.04

**Comment by paskal** [comment]
[Build in progress](https://code.launchpad.net/~paskal-07/+archive/ubuntu/softethervpn/+build/15529757). My suggestion is to leave this hack in place for case of glibc < v2.16. It worth nothing to have it but increase range of places it could be compiled without problems.

**Comment by chipitsine** [comment]
@paskal , can you provide a patch with `glibc < v2.16` condition ?

**Comment by paskal** [comment]
I'll see what I can do. You don't want this workaround to be present in upstream, am I got you correctly?

**Comment by chipitsine** [comment]
in upstream we have gitlab-ci, as long as 12.04 is available in docker registry, we can use it. patch is ugly, but I'd keep it in upstream (after review by @davidebeatrici  )

**Comment by chipitsine** [comment]
I need to fix that https://travis-ci.org/chipitsine/SoftEtherVPN/jobs/440103524

**Comment by chipitsine** [comment]
https://github.com/chipitsine/SoftEtherVPN/commit/b25408fa911d5ffb2bb8da5c049484bf05b15e24

**Comment by paskal** [comment]
Ilya, if that's it could you please prepare proper PR to mainland so Davide will be able to review it trough the standard procedure? Also I've lost the ability to build package from your repo because it's now missing separate tree for the feature.

**Comment by davidebeatrici** [comment]
SoftEtherVPN/SoftEtherVPN/pull/744

**Comment by paskal** [comment]
Thanks everyone! Switched build back to upstream and learned about gitlab ci\cd feature for external repos:)
